block-gravity:
  enabled: false # true - Gravity Enabled | false - Gravity Disabled
  disabled-worlds: # List of worlds in which the plugin will not work
    - exampleWorld1
    - exampleWorld2

fluids-gravity:
  enabled: false # true - Gravity Enabled | false - Gravity Disabled
  disabled-worlds: # List of worlds in which the plugin will not work
    - exampleWorld1
    - exampleWorld2